name: Execute Go Tests

on:
  pull_request:
    branches: [main]

jobs:
  setup-build-publish-deploy:
    name: Execute Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Go Unit Tests
        run: go test ./app/...

      - name: Run Go E2E Tests
        run: go test ./test/...
