name: Execute Go Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
  unit_test:
    name: Execute Go Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Go Unit Tests
        run: go test ./app/...
